# https://www.kaggle.com/learn/pandas

In [1]:
import pandas as pd
import numpy as np
pd.set_option('max_columns', 60)
pd.set_option('max_row',5)

In [2]:
pwd

'C:\\Users\\nguye\\Pandas'

In [3]:
import os
os.chdir('E:\PYTHON')

In [4]:
pwd

'E:\\PYTHON'

In [5]:
dt=pd.read_csv(r'E:\PYTHON\311_Service_Requests_for_2009.csv',low_memory=False)

In [6]:
display(dt.head(1),dt.shape)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,Intersection Street 2,Address Type,City,Landmark,Facility Type,Status,Due Date,Resolution Action Updated Date,Community Board,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Park Facility Name,Park Borough,School Name,School Number,School Region,School Code,School Phone Number,School Address,School City,School State,School Zip,School Not Found,School or Citywide Complaint,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,12824180,01/01/2009 12:00:00 AM,01/08/2009 12:00:00 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,01/15/2009 12:00:00 AM,01/08/2009 12:00:00 AM,12 MANHATTAN,MANHATTAN,NaN,NaN,Fort Tryon Park,MANHATTAN,Fort Tryon Park,M029,NaN,NaN,2124080100,"Riverside Drive to Broadway, West 192nd to Dyc...",NEW YORK,NY,10033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(1783133, 52)

In [7]:
dt.set_axis([i.lower() for i in dt.columns],1,inplace=True)
dt

,unique key,created date,closed date,agency,agency name,complaint type,descriptor,location type,incident zip,incident address,street name,cross street 1,cross street 2,intersection street 1,intersection street 2,address type,city,landmark,facility type,status,due date,resolution action updated date,community board,borough,x coordinate (state plane),y coordinate (state plane),park facility name,park borough,school name,school number,school region,school code,school phone number,school address,school city,school state,school zip,school not found,school or citywide complaint,vehicle type,taxi company borough,taxi pick up location,bridge highway name,bridge highway direction,road ramp,bridge highway segment,garage lot name,ferry direction,ferry terminal name,latitude,longitude,location
0,12824180,01/01/2009 12:00:00 AM,01/08/2009 12:00:00 AM,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NEW YORK,NaN,NaN,Closed,01/15/2009 12:00:00 AM,01/08/2009 12:00:00 AM,12 MANHATTAN,MANHATTAN,NaN,NaN,Fort Tryon Park,MANHATTAN,Fort Tryon Park,M029,NaN,NaN,2124080100,"Riverside Drive to Broadway, West 192nd to Dyc...",NEW YORK,NY,10033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12882475,01/08/2009 12:00:00 AM,01/08/2009 12:00:00 AM,DOT,Department of Transportation,Street Light Condition,Street Light Out,NaN,NaN,NaN,NaN,NaN,NaN,4 ST W,AVE U,INTERSECTION,NaN,NaN,NaN,Closed,NaN,01/07/2009 12:00:00 AM,Unspecified BROOKLYN,BROOKLYN,NaN,NaN,Unspecified,BROOKLYN,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1783131,14039954,05/26/2009 12:00:00 AM,05/28/2009 12:00:00 AM,HPD,Department of Housing Preservation and Develop...,PAINT - PLASTER,CEILING,RESIDENTIAL BUILDING,10031,610 RIVERSIDE DRIVE,RIVERSIDE DRIVE,WEST 138 STREET,WEST 139 STREET,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,NaN,05/28/2009 12:00:00 AM,0 Unspecified,Unspecified,996519.0,239117.0,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.822988,-73.955671,"(40.822987992537, -73.955670659316)"
1783132,14161381,06/11/2009 12:00:00 AM,06/11/2009 12:00:00 AM,DOB,Department of Buildings,Electrical,Electrical Wiring Defective/Exposed,NaN,10467,2324 BOSTON ROAD,BOSTON ROAD,ASTOR AVENUE,WARING AVENUE,NaN,NaN,ADDRESS,BRONX,NaN,NaN,Closed,NaN,06/11/2009 12:00:00 AM,11 BRONX,BRONX,1020987.0,252703.0,Unspecified,BRONX,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.860210,-73.867191,"(40.860209679066, -73.867190562678)"

In [8]:
import re
li=sorted([re.sub(' ','',i).lower() for i in dt.columns])
li

['addresstype',
 'agency',
 'agencyname',
 'borough',
 'bridgehighwaydirection',
 'bridgehighwayname',
 'bridgehighwaysegment',
 'city',
 'closeddate',
 'communityboard',
 'complainttype',
 'createddate',
 'crossstreet1',
 'crossstreet2',
 'descriptor',
 'duedate',
 'facilitytype',
 'ferrydirection',
 'ferryterminalname',
 'garagelotname',
 'incidentaddress',
 'incidentzip',
 'intersectionstreet1',
 'intersectionstreet2',
 'landmark',
 'latitude',
 'location',
 'locationtype',
 'longitude',
 'parkborough',
 'parkfacilityname',
 'resolutionactionupdateddate',
 'roadramp',
 'schooladdress',
 'schoolcity',
 'schoolcode',
 'schoolname',
 'schoolnotfound',
 'schoolnumber',
 'schoolorcitywidecomplaint',
 'schoolphonenumber',
 'schoolregion',
 'schoolstate',
 'schoolzip',
 'status',
 'streetname',
 'taxicompanyborough',
 'taxipickuplocation',
 'uniquekey',
 'vehicletype',
 'xcoordinate(stateplane)',
 'ycoordinate(stateplane)']

In [9]:
dt.loc[dt['location type']=='Park',['unique key','location type']]

         unique key location type
0          12824180          Park
12         12824945          Park
...             ...           ...
1782608    13312667          Park
1782809    14679147          Park

[10120 rows x 2 columns]

In [10]:
dt['incident zip'].str.contains('[^0-9]')

0          False
1            NaN
           ...
1783131    False
1783132    False
Name: incident zip, Length: 1783133, dtype: object

In [105]:
dt[~(dt['incident zip'].fillna('-')).str.contains('\D')]['incident zip'].unique()

array(['10033', '11216', '10010', '11209', '07030', '10027', '10002',
       '07927', '10023', '11375', '11220', '10458', '10456', '10471',
       '11224', '11235', '10462', '23502', '12345', '44113', '11236',
       '07632', '10550', '11214', '30328', '10472', '10025', '11581',
       '11377', '11735', '20850', '10028', '11766', '10021', '11797',
       '07020', '11366', '11361', '11426', '11549', '10459', '55344',
       '11215', '11434', '10039', '07302', '10467', '18773', '10004',
       '92683', '10024', '33319', '11201', '10035', '11218', '11749',
       '11356', '10012', '11205', '00000', '15561', '10304', '10457',
       '10003', '10468', '10305', '10309', '19850', '84117', '56303',
       '11211', '11692', '10026', '08003', '07114', '11530', '11590',
       '11561', '11772', '11368', '10029', '07962', '85004', '75234',
       '14009', '11219', '11354', '11360', '0000', '19044', '11355',
       '11419', '11105', '11102', '10301', '10031', '07301', '11231',
       '77081', '63043', '11747', '14227', '11230', '11598', '77272',
       '10014', '10306', '10704', '17111', '11358', '11238', '11413',
       '10460', '10705', '32750', '11203', '11362', '02360', '07470',
       '10013', '13209', '08055', '07104', '07054', '46219', '11693',
       '11691', '10469', '14225', '07111', '43614', '11729', '10463',
       '55426', '08904', '11423', '10314', '14221', '94524', '74175',
       '10452', '11001', '08691', '11421', '10465', '11379', '10001',
       '02061', '10034', '11411', '11233', '10461', '11096', '10453',
       '11372', '11412', '55441', '11570', '11701', '11217', '23219',
       '07071', '11385', '10523', '11357', '07102', '07627', '10009',
       '07307', '07731', '11204', '14305', '11210', '11234', '10128',
       '07724', '10308', '10011', '78682', '92056', '11010', '11414',
       '19154', '55205', '75266', '07087', '11237', '10312', '19456',
       '77074', '14210', '11433', '30360', '10801', '89434', '23703',
       '55439', '11556', '07047', '17106', '11229', '94111', '11226',
       '11221', '10455', '95402', '10038', '10307', '10032', '10950',
       '32256', '07646', '10454', '11756', '10473', '07083', '79998',
       '07631', '11536', '11206', '11694', '44122', '75063', '11212',
       '11207', '11559', '07086', '61702', '11432', '11104', '21230',
       '11803', '11030', '32524', '23260', '10159', '14240', '14623',
       '11572', '60656', '06510', '11365', '14228', '10970', '55164',
       '32211', '15250', '11553', '11106', '08650', '07201', '11542',
       '73135', '07024', '48090', '11787', '11213', '08701', '11370',
       '11222', '33321', '78278', '02459', '60630', '11101', '11422',
       '198884', '10451', '10303', '75091', '33487', '08053', '11223',
       '11232', '60714', '23541', '10020', '11378', '10022', '11771',
       '11042', '43236', '10577', '10280', '92123', '11510', '11103',
       '44139', '43231', '75243', '07110', '11802', '10007', '11228',
       '19904', '10017', '15108', '08091', '07960', '00919', '33330',
       '30339', '11416', '31139', '07039', '10803', '10037', '29601',
       '14043', '98006', '50701', '11208', '11430', '18504', '78501',
       '10044', '10016', '02205', '11516', '30996', '070545020',
       '402901921', '07663', '103', '15219', '03079', '32255', '10466',
       '11040', '30092', '33405', '10310', '14850', '77253', '94942',
       '10036', '78704', '11021', '30004', '11364', '11580', '48195',
       '10040', '34025', '19047', '55420', '64501', '10000', '60605',
       '07310', '10710', '11763', '78006', '11004', '11563', '301447802',
       '31146', '12551', '89119', '11023', '10019', '63301', '90509',
       '07073', '55125', '07650', '11418', '19886', '14450', '90006',
       '11704', '10530', '10030', '000000', '10018', '11776', '11417',
       '94901', '44131', '74355', '23320', '11367', '11015', '55127',
       '11566', '85040', '21093', '11420', '171060', '30071', '38184',
       '56379', '00914', '10533', '60601', '12524', '11436', '10591',
       '10954', '17038', '20090', '483931022', '93389', '10474', '11373',
       '55113', '07660', '95476', '07361', '93721', '38016', '11746',
       '01748', '08086', '60148', '11550', '98007', '98036', '14424',
       '60076', '75006', '16368', '07017', '90621', '98057', '18966',
       '76155', '23285', '45040', '13320', '27410', '10553', '10602',
       '11363', '75090', '21014', '10464', '11225', '48237', '07002',
       '78708', '432182273', '43218', '43226', '99999', '11374', '07010',
       '10594', '11429', '07375', '10302', '33469', '10552', '39466',
       '33771', '01845', '07093', '07004', '27216', '11435', '13850',
       '11768', '10708', '90060', '91309', '07095', '11369', '11791',
       '59901', '07091', '12428', '14614', '07306', '10567', '11554',
       '65205', '10532', '33765', '112230', '53008', '11552', '07206',
       '80246', '77060', '12590', '07546', '80202', '11801', '74170',
       '30062', '07103', '50037', '70006', '11239', '48034', '10707',
       '60154', '30009', '10274', '01666', '46278', '07094', '111111',
       '33716', '10605', '11951', '07305', '60168', '11111', '38057',
       '60204', '30067', '06490', '11507', '33486', '77072', '11024',
       '63017', '12255', '06901', '30305', '92408', '10006', '14213',
       '11003', '11359', '11710', '33314', '94509', '11520', '57117',
       '10604', '10502', '11741', '10573', '07711', '90630', '85385',
       '90049', '07063', '44143', '10703', '160077', '85282', '92108',
       '11788', '11782', '11793', '07670', '10512', '17706', '10286',
       '01842', '11739', '944551', '10930', '80014', '10977', '14231',
       '11557', '80217', '11762', '30304', '95825', '10601', '06260',
       '11425', '85302', '386555442', '10603', '02494', '10528', '222222',
       '10549', '08002', '09253', '07932', '01843', '12203', '84130',
       '33155', '07092', '07609', '01544', '07876', '90272', '10805',
       '77437', '01105', '75801', '07407', '28078', '55433', '11576',
       '19053', '63042', '21050', '11795', '11742', '11714', '32239',
       '11753', '07101', '08824', '85731', '23462', '07031', '11784',
       '1108', '75225', '60191', '50309', '11573', '11780', '11565',
       '12227', '32401', '44685', '02150', '30189', '14120', '30564',
       '10924', '13081', '55438', '10069', '77006', '07090', '11779',
       '10163', '03101', '33329', '08735', '02132', '08731', '10701',
       '07079', '63006', '7998143', '94551', '12533', '11725', '00174',
       '11777', '07340', '38814', '07003', '1001', '14845', '80111',
       '55175', '11757', '52411', '11652', '98021', '37615', '07018',
       '67504', '607141', '28590', '43243', '48093', '01624', '799981438',
       '43216', '07304', '11240', '85069', '92046', '92203', '10065',
       '11743', '89102', '100000', '24022', '10606', '77056', '30097',
       '21220', '32896', '45202', '10709', '01810', '73155', '14219',
       '28272', '47130', '008701', '01830', '07981', '21297', '09211',
       '35203', '08540', '85001', '95650', '08754', '38116', '11575',
       '07076', '32541', '07901', '18017', '78228', '14068', '51591',
       '11518', '11501', '33610', '43232', '11758', '11767', '44146',
       '75024', '11438', '70459', '07748', '85064', '95834', '14611',
       '14217', '00', '19067', '33029', '68106', '33901', '11371',
       '11415', '10470', '10005', '11428', '10075', '11427', '10475',
       '11697', '10048', '11109', '10282', '11243', '11005', '10281',
       '10162', '11241', '10400', '11600', '11695', '07008', '11242'],
      dtype=object)

In [108]:
dt.de

ValueError: cannot convert float NaN to integer