In [1]:
import numpy as np
import pandas as pd

In [6]:
dt=pd.read_excel(r'C:\Users\nguye\Downloads\PET_daily_1961_2018.xlsx', sheet_name='data')
dt.head(3)

,Date,Month_year,2011,2050,2076,2093,2110,2153,2200,2210,...,2866,2867,2869,2870,2871,2873,2875,2877,2880,2905
0,1961-01-01,1_1961,165.584577,167.650284,187.378039,169.198019,174.676444,196.950907,181.081021,172.393514,...,238.775894,233.381387,227.097253,231.859641,236.175284,235.678143,226.876288,227.862879,215.580449,200.258849
1,1961-01-02,1_1961,117.275272,119.742986,133.857587,118.822137,124.420359,142.933482,132.478742,126.279497,...,185.567705,185.114825,188.059840,186.367719,189.234305,198.891140,189.451132,197.543406,203.325481,147.526442
2,1961-01-03,1_1961,131.974419,133.826767,141.432860,131.926868,136.569315,148.069522,142.334058,138.508123,...,158.087061,161.284492,170.748526,169.905679,174.428072,167.750834,173.112088,159.135466,159.033165,146.005051

In [45]:
dt1=dt.groupby('Month_year').mean()
dt1

,2011,2050,2076,2093,2110,2153,2200,2210,2250,2259,...,2866,2867,2869,2870,2871,2873,2875,2877,2880,2905
Month_year,,,,,,,,,,,,,,,,,,,,,
10_1961,99.706327,101.102555,108.880974,100.463755,104.194191,114.253878,108.458819,104.908800,107.357252,102.287946,...,124.143184,123.977659,128.915615,128.200775,132.608904,136.713361,133.053801,137.738901,143.463459,110.212408
10_1962,90.545730,91.534972,97.420249,91.153167,94.055501,101.405129,96.893566,94.140037,94.793703,89.633859,...,98.373401,99.322301,106.561769,105.809117,111.018767,113.486313,112.114234,115.122692,122.287865,85.754456
10_1963,101.542745,103.011578,110.214375,102.031101,105.934312,115.604799,110.288677,106.895448,107.019929,101.249525,...,119.487436,118.639598,122.991574,123.526576,129.211912,130.835225,128.195992,133.459137,137.484500,110.233538
10_1964,98.826848,99.808115,106.127479,99.607278,102.502693,110.074256,105.211305,102.361049,105.608591,101.319319,...,103.916341,104.587475,110.208581,107.645753,110.760243,118.384199,112.109287,116.181392,124.459228,86.548959
10_1965,91.281165,92.972158,102.629881,92.506775,96.681425,108.470262,101.619224,97.468483,103.910286,99.537957,...,128.229343,128.754738,135.339149,132.366913,135.279704,140.733494,137.323563,139.425866,147.118498,108.366606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9_2014,92.767654,93.738673,99.376003,93.415351,96.506936,103.726425,99.545796,96.872058,99.048099,95.851728,...,99.083748,100.707010,108.991098,104.317939,106.735097,115.294549,111.363851,110.715304,115.477057,88.240960
9_2015,93.158352,94.290038,100.143032,93.700674,97.140969,104.949815,100.746320,97.970667,99.551525,96.220610,...,104.402638,105.456469,112.907321,107.727721,108.910003,118.611220,113.519023,112.539798,122.068322,94.348048
9_2016,83.552815,84.382327,89.765379,84.296111,87.064863,93.589043,89.812595,87.322198,88.972977,85.783029,...,77.207420,76.100164,80.220197,76.449485,77.992108,83.738612,79.890114,78.521835,90.511899,74.075860
9_2017,114.651240,115.344527,120.755611,115.497465,118.179938,124.521238,120.238480,117.724204,122.586433,121.091847,...,112.074139,113.650361,121.958745,115.797339,117.757388,127.754186,122.174292,124.832215,132.527980,94.542923
9_2018,90.160922,91.229949,96.322100,90.481190,93.738690,100.885732,97.020317,94.509308,95.366151,91.703176,...,99.147024,100.972324,108.886590,105.327656,107.604991,113.275664,109.497259,109.045044,113.114486,89.780564

In [52]:
dt1.to_excel(r'C:\Users\nguye\Downloads\ea.xlsx')

In [64]:
dt3=pd.read_excel(r'C:\Users\nguye\Downloads\ea.xlsx')
dt3

,Month_year,2011,2050,2076,2093,2110,2153,2200,2210,2250,...,2866,2867,2869,2870,2871,2873,2875,2877,2880,2905
0,10_1961,99.706327,101.102555,108.880974,100.463755,104.194191,114.253878,108.458819,104.908800,107.357252,...,124.143184,123.977659,128.915615,128.200775,132.608904,136.713361,133.053801,137.738901,143.463459,110.212408
1,10_1962,90.545730,91.534972,97.420249,91.153167,94.055501,101.405129,96.893566,94.140037,94.793703,...,98.373401,99.322301,106.561769,105.809117,111.018767,113.486313,112.114234,115.122692,122.287865,85.754456
2,10_1963,101.542745,103.011578,110.214375,102.031101,105.934312,115.604799,110.288677,106.895448,107.019929,...,119.487436,118.639598,122.991574,123.526576,129.211912,130.835225,128.195992,133.459137,137.484500,110.233538
3,10_1964,98.826848,99.808115,106.127479,99.607278,102.502693,110.074256,105.211305,102.361049,105.608591,...,103.916341,104.587475,110.208581,107.645753,110.760243,118.384199,112.109287,116.181392,124.459228,86.548959
4,10_1965,91.281165,92.972158,102.629881,92.506775,96.681425,108.470262,101.619224,97.468483,103.910286,...,128.229343,128.754738,135.339149,132.366913,135.279704,140.733494,137.323563,139.425866,147.118498,108.366606
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,9_2014,92.767654,93.738673,99.376003,93.415351,96.506936,103.726425,99.545796,96.872058,99.048099,...,99.083748,100.707010,108.991098,104.317939,106.735097,115.294549,111.363851,110.715304,115.477057,88.240960
692,9_2015,93.158352,94.290038,100.143032,93.700674,97.140969,104.949815,100.746320,97.970667,99.551525,...,104.402638,105.456469,112.907321,107.727721,108.910003,118.611220,113.519023,112.539798,122.068322,94.348048
693,9_2016,83.552815,84.382327,89.765379,84.296111,87.064863,93.589043,89.812595,87.322198,88.972977,...,77.207420,76.100164,80.220197,76.449485,77.992108,83.738612,79.890114,78.521835,90.511899,74.075860
694,9_2017,114.651240,115.344527,120.755611,115.497465,118.179938,124.521238,120.238480,117.724204,122.586433,...,112.074139,113.650361,121.958745,115.797339,117.757388,127.754186,122.174292,124.832215,132.527980,94.542923
695,9_2018,90.160922,91.229949,96.322100,90.481190,93.738690,100.885732,97.020317,94.509308,95.366151,...,99.147024,100.972324,108.886590,105.327656,107.604991,113.275664,109.497259,109.045044,113.114486,89.780564

In [66]:
import re

In [76]:
li=[]
for i in dt3['Month_year']:
    li.append(re.sub('_',"-",i))

In [85]:
dt3['m-y']=li

In [91]:
dt3.drop('Month_year',1)

,2011,2050,2076,2093,2110,2153,2200,2210,2250,2259,...,2867,2869,2870,2871,2873,2875,2877,2880,2905,m-y
10-1961,99.706327,101.102555,108.880974,100.463755,104.194191,114.253878,108.458819,104.908800,107.357252,102.287946,...,123.977659,128.915615,128.200775,132.608904,136.713361,133.053801,137.738901,143.463459,110.212408,10-1961
10-1962,90.545730,91.534972,97.420249,91.153167,94.055501,101.405129,96.893566,94.140037,94.793703,89.633859,...,99.322301,106.561769,105.809117,111.018767,113.486313,112.114234,115.122692,122.287865,85.754456,10-1962
10-1963,101.542745,103.011578,110.214375,102.031101,105.934312,115.604799,110.288677,106.895448,107.019929,101.249525,...,118.639598,122.991574,123.526576,129.211912,130.835225,128.195992,133.459137,137.484500,110.233538,10-1963
10-1964,98.826848,99.808115,106.127479,99.607278,102.502693,110.074256,105.211305,102.361049,105.608591,101.319319,...,104.587475,110.208581,107.645753,110.760243,118.384199,112.109287,116.181392,124.459228,86.548959,10-1964
10-1965,91.281165,92.972158,102.629881,92.506775,96.681425,108.470262,101.619224,97.468483,103.910286,99.537957,...,128.754738,135.339149,132.366913,135.279704,140.733494,137.323563,139.425866,147.118498,108.366606,10-1965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9-2014,92.767654,93.738673,99.376003,93.415351,96.506936,103.726425,99.545796,96.872058,99.048099,95.851728,...,100.707010,108.991098,104.317939,106.735097,115.294549,111.363851,110.715304,115.477057,88.240960,9-2014
9-2015,93.158352,94.290038,100.143032,93.700674,97.140969,104.949815,100.746320,97.970667,99.551525,96.220610,...,105.456469,112.907321,107.727721,108.910003,118.611220,113.519023,112.539798,122.068322,94.348048,9-2015
9-2016,83.552815,84.382327,89.765379,84.296111,87.064863,93.589043,89.812595,87.322198,88.972977,85.783029,...,76.100164,80.220197,76.449485,77.992108,83.738612,79.890114,78.521835,90.511899,74.075860,9-2016
9-2017,114.651240,115.344527,120.755611,115.497465,118.179938,124.521238,120.238480,117.724204,122.586433,121.091847,...,113.650361,121.958745,115.797339,117.757388,127.754186,122.174292,124.832215,132.527980,94.542923,9-2017
9-2018,90.160922,91.229949,96.322100,90.481190,93.738690,100.885732,97.020317,94.509308,95.366151,91.703176,...,100.972324,108.886590,105.327656,107.604991,113.275664,109.497259,109.045044,113.114486,89.780564,9-2018